version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0.2

workflows:
  main:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/review:
          exclude: "RC005,RC010"
      - orb-tools/publish:
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
          filters:
            branches:
              only: main

          orb_name: stackbuilders/stack-build
          vcs_type: github
