version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0.2

workflows:
  main:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish:
          orb_name: stackbuilders/stack-build
          requires: [orb-tools/pack, orb-tools/lint]
          vcs_type: github
