version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0.2

workflows:
  main:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish:
          requires:
            - orb-tools/pack
          filter:
            branches:
              - main

          orb_name: stackbuilders/stack-build
          vcs_type: github
