---
description: |
  Build the project

parameters:
  stack_yaml:
    description: "Path to stack.yaml file to use"
    type: string
    default: stack.yaml
  stack_arguments:
    description: "Additional arguments for ALL Stack invocations"
    type: string
    default: "--pedantic"
  weeder:
    description: "Run Weeder?"
    type: boolean
    default: true
  cache_prefix:
    description: "Prefix used for cache key"
    type: string
    default: v1

steps:
  - restore_cache:
      keys:
        - <<parameters.cache_prefix>>-{{ checksum "<<parameters.stack_yaml>>" }}-{{ checksum "project.digest" }}-{{ checksum "source.digest" }}
        - <<parameters.cache_prefix>>-{{ checksum "<<parameters.stack_yaml>>" }}-{{ checksum "project.digest" }}
        - <<parameters.cache_prefix>>-{{ checksum "<<parameters.stack_yaml>>" }}-
  - run:
      name: Build
      environment:
        PARAM_STACK_ARGUMENTS: <<parameters.stack_arguments>>
        PARAM_STACK_YAML: <<parameters.stack_yaml>>
      command: <<include(scripts/build.sh)>>
  - save_cache:
      key: <<parameters.cache_prefix>>-{{ checksum "<<parameters.stack_yaml>>" }}-{{ checksum "project.digest" }}-{{ checksum "source.digest" }}
      paths:
        - ./.stack_work
