---
description: |
  Build the project

parameters:
  stack-yaml:
    description: "Path to stack.yaml file to use"
    type: string
    default: stack.yaml
  stack-arguments:
    description: "Additional arguments for ALL Stack invocations"
    type: string
    default: "--pedantic"
  weeder:
    description: "Run Weeder?"
    type: boolean
    default: true
  cache-prefix:
    description: "Prefix used for cache key"
    type: string
    default: v1

steps:
  - restore_cache:
      keys:
        - <<parameters.cache-prefix>>-{{ checksum "<<parameters.stack-yaml>>" }}-{{ checksum "project.digest" }}-{{ checksum "source.digest" }}
        - <<parameters.cache-prefix>>-{{ checksum "<<parameters.stack-yaml>>" }}-{{ checksum "project.digest" }}
        - <<parameters.cache-prefix>>-{{ checksum "<<parameters.stack-yaml>>" }}-
  - run:
      name: Build
      environment:
        PARAM_STACK_ARGUMENTS: <<parameters.stack-arguments>>
        PARAM_STACK_YAML: <<parameters.stack-yaml>>
      command: <<include(scripts/build.sh)>>
  - save_cache:
      key: <<parameters.cache-prefix>>-{{ checksum "<<parameters.stack-yaml>>" }}-{{ checksum "project.digest" }}-{{ checksum "source.digest" }}
      paths:
        - ./.stack-work
